### ISSUE TITLE
Emoji: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by Udayendu** [imzbf/md-editor-rt#149]
### Describe the issue

For Emoji, I am getting the following warning:

```
Each child in a list should have a unique "key" prop
```

Here is now I am defining the custom toolbars:

```
import { MdEditor } from "md-editor-rt";
import "md-editor-rt/lib/style.css";
import { OriginalImg } from "@vavt/rt-extension";
import { Emoji } from "@vavt/rt-extension";
import { Mark } from "@vavt/rt-extension";
import "@vavt/rt-extension/lib/asset/Emoji.css";
```

```
const customToolbars = [
    <OriginalImg
      key="OriginalImg"
      trigger={<span className="mee-iconfont icon-mee-tupian" />}
      title="imgresize"
    />,
    <Mark
      key="Mark"
      trigger={<span className="mee-iconfont icon-mee-mark" />}
      title="mark"
    />,
    <Emoji
      key="Emoji"
      trigger={<span className="mee-iconfont icon-mee-emoji" />}
      title="emoji"
      selectAfterInsert={false}
    />,
  ];
```

Then in the MdEditor, I am invoking like below:

```
<MdEditor
            theme="light"
            language="en-US"
            previewTheme="github"
            noHighlight="true"
            modelValue={contentdescription}
            onChange={(modelValue) => {
              handleContent(modelValue);
            }}
            toolbars={[
              "bold",
              "underline",
              "italic",
              "-",
              "strikeThrough",
              "sub",
              "sup",
              "quote",
              "unorderedList",
              "orderedList",
              "task",
              "-",
              "codeRow",
              "code",
              "link",
              "image",
              "table",
              "mermaid",
              "katex",
              "0",
              "1",
              "2",
              "-",
              "revoke",
              "next",
              "save",
              "=",
              "prettier",
              "pageFullscreen",
              "fullscreen",
              "preview",
              "htmlPreview",
              "catalog",
              "github",
            ]}
            toolbarsExclude={["htmlPreview", "catalog", "github"]}
            scrollAuto="true"
            autoDetectCode="true"
            defToolbars={customToolbars}
          />
```

For image resize and mark, there is no issue. Its just coming for the emoji. 

### Procedure version

4.13.3

**Comment by Udayendu** [comment]
@imzbf , after upgrading to v4.13.4 the issue still persists. My Editor is wrapped inside a FormControl.

```
<FormControl fullWidth margin="normal">
</FormControl>
```

The config of MdEditor is available in the description. Am I doing anything wrong ?

**Comment by imzbf** [comment]
> @imzbf , after upgrading to v4.13.4 the issue still persists. My Editor is wrapped inside a FormControl.
> 
> ```
> <FormControl fullWidth margin="normal">
> </FormControl>
> ```
> 
> The config of MdEditor is available in the description. Am I doing anything wrong ?

Did you install new version of `@vavt/rt-extension`?

**Comment by Udayendu** [comment]
> > @imzbf , after upgrading to v4.13.4 the issue still persists. My Editor is wrapped inside a FormControl.
> > ```
> > <FormControl fullWidth margin="normal">
> > </FormControl>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The config of MdEditor is available in the description. Am I doing anything wrong ?
> 
> Did you install new version of `@vavt/rt-extension`?

Nope. Let me try that.

**Comment by Udayendu** [comment]
After upgrading, I am getting the below error now:

```
Cannot find module '@vavt/rt-extension/lib/asset/Emoji.css'
    at webpackMissingModule (http://localhost:3000/static/js/bundle.js:9697:50)
    at ./src/dashboard/LandingPage/Pages/CreatePage.jsx (http://localhost:3000/static/js/bundle.js:9697:163)
    at options.factory (http://localhost:3000/static/js/bundle.js:220230:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:219629:32)
    at fn (http://localhost:3000/static/js/bundle.js:219888:21)
    at ./src/App.js (http://localhost:3000/static/js/bundle.js:544:97)
    at options.factory (http://localhost:3000/static/js/bundle.js:220230:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:219629:32)
    at fn (http://localhost:3000/static/js/bundle.js:219888:21)
    at ./src/index.js (http://localhost:3000/static/js/bundle.js:16372:62)
```

But as per https://github.com/imzbf/md-editor-extension/blob/main/packages/rt/components/Emoji/README.md the path seems to be correct.

```
import { MdEditor, config } from "md-editor-rt";
import "md-editor-rt/lib/style.css";
import { OriginalImg } from "@vavt/rt-extension";
import { Emoji } from "@vavt/rt-extension";
import { Mark } from "@vavt/rt-extension";
import MarkExtension from "markdown-it";
import "@vavt/rt-extension/lib/asset/Emoji.css";
```

These are my imports.

**Comment by Udayendu** [comment]
Seems like the path has been changed in the code. This is what I can see now:

```
import "@vavt/rt-extension/lib/asset/Emoji-style.css";
```

![image](https://github.com/imzbf/md-editor-rt/assets/1809177/8f799524-b5eb-404a-b336-4ef25a9c461d)

**Comment by imzbf** [comment]
I rolled back the issue with the path. Reinstall `@vavt/rt-extension`

Can you provide an environment for restoring the problem, as I have experimented with the `dev-docs` branch and cannot find the problem

**Comment by Udayendu** [comment]
> I rolled back the issue with the path. Reinstall `@vavt/rt-extension`
> 
> Can you provide an environment for restoring the problem, as I have experimented with the `dev-docs` branch and cannot find the problem

After installing the `"@vavt/rt-extension": "^1.2.1"` the Emoji.css path issue has been resolved. But the key error is still available.

**Comment by Udayendu** [comment]
> I rolled back the issue with the path. Reinstall `@vavt/rt-extension`
> 
> Can you provide an environment for restoring the problem, as I have experimented with the `dev-docs` branch and cannot find the problem

@imzbf , I just tested this editor by creating a new project and its 100% reproducible. 
Here is what I did to reproduce it:

- npx create-react-app editorbug
- cd editorbug/
- npm i
- npm start
- npm install @mui/material @emotion/react @emotion/styled
- npm install md-editor-rt
- npm install @vavt/rt-extension

Then in App.js, remove everything and use the data as I have mentioned in the bug description, you should be able to see it.

My App.js us looking something like this:

```
import "./App.css";
import MarkdownEditor from "./MarkdownEditor";

function App() {
  return (
    <div className="App">
      <MarkdownEditor />
    </div>
  );
}

export default App;
```

and MarkdownEditor.jsx is like below:

```
import React, { useState } from "react";
import { MdEditor } from "md-editor-rt";
import "md-editor-rt/lib/style.css";
import { OriginalImg } from "@vavt/rt-extension";
import { Emoji } from "@vavt/rt-extension";
import { Mark } from "@vavt/rt-extension";
import "@vavt/rt-extension/lib/asset/Emoji.css";
import { FormControl } from "@mui/material";

const MarkdownEditor = () => {
  const [markdown, setMarkdown] = useState("");

  const customToolbars = [
    <OriginalImg
      key="OriginalImg"
      trigger={<span className="mee-iconfont icon-mee-tupian" />}
      title="imgresize"
    />,
    <Mark
      key="Mark"
      trigger={<span className="mee-iconfont icon-mee-mark" />}
      title="mark"
    />,
    <Emoji
      key="Emoji"
      trigger={<span className="mee-iconfont icon-mee-emoji" />}
      title="emoji"
      selectAfterInsert={false}
    />,
  ];

  return (
    <div>
      <FormControl fullWidth margin="normal">
        <MdEditor
          theme="light"
          language="en-US"
          previewTheme="github"
          noHighlight="true"
          modelValue={markdown}
          toolbars={[
            "bold",
            "underline",
            "italic",
            "strikeThrough",
            "-",
            "title",
            "sub",
            "sup",
            "quote",
            "unorderedList",
            "orderedList",
            "task",
            "-",
            "codeRow",
            "code",
            "link",
            "image",
            "table",
            "mermaid",
            "katex",
            "0",
            "1",
            "2",
            "-",
            "revoke",
            "next",
            "save",
            "=",
            "prettier",
            "pageFullscreen",
            "fullscreen",
            "preview",
            "htmlPreview",
            "catalog",
            "github",
          ]}
          toolbarsExclude={["htmlPreview", "catalog", "github"]}
          scrollAuto="true"
          autoDetectCode="true"
          defToolbars={customToolbars}
        />
      </FormControl>
    </div>
  );
};

export default MarkdownEditor;
```

**Comment by imzbf** [comment]
Try 4.13.5

**Comment by Udayendu** [comment]
> Try 4.13.5

Still the key error issue persist. Can you check if I am using `defToolbars={customToolbars}` correctly or not.

**Comment by imzbf** [comment]
We also need it here

```diff
-trigger={<span className="mee-iconfont icon-mee-emoji" />}
+trigger={<span key="123" className="mee-iconfont icon-mee-emoji" />}
```

**Comment by Udayendu** [comment]
> We also need it here
> 
> ```diff
> -trigger={<span className="mee-iconfont icon-mee-emoji" />}
> +trigger={<span key="123" className="mee-iconfont icon-mee-emoji" />}
> ```

Yes, after applying this change it started working now.
